### ISSUE TITLE
[🐛 Bug Report]: WC5 Drag to bottom Pushes apostle outside of Map

### ISSUE THREAD

**Issue by bikutaaaa** [FoonieMagus/ApeironBattleDemo_IssueList#103] opened 2024-02-10 07:13 UTC
### Demo Environment

Production

### Battle Demo Version

v0.5.157

### System Environment

na

### What is expected?

Apostle stays inside map

### What is happening?

Apostle pushed outside map

### Reproducible Bugs

Yes

### Related link

https://drive.google.com/file/d/1srK25VUXlZwhFS9FNlDn2bvqFtIJVd97/view?usp=sharing

### Additional info

https://drive.google.com/file/d/1srK25VUXlZwhFS9FNlDn2bvqFtIJVd97/view?usp=sharing

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeiron-doodaria) channel and reference the specific issue on Github.

**Comment by gemscng** [comment] 2024-02-15 05:21
duplicate of https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues/93

**Closed as completed by gemscng** 2024-02-15 05:21 UTC
Labels: bug, production
