### ISSUE TITLE
[🐛 Bug Report]: Earth c1 bug with red zone

### ISSUE THREAD

**Issue by Pepecrazy** [FoonieMagus/ApeironBattleDemo_IssueList#86] opened 2024-01-31 02:42 UTC
### Demo Environment

Beta Test

### Battle Demo Version

v0.5.124

### System Environment

Windows 10, Ryzen 5600g

### What is expected?

bug with Earth c1 Rock'n'Roll 

### What is happening?

i have tested: in red zone Earth c1 bugging (ONLY if learnt 7/7) if it get destroyed by red zone - its become immortal but every tick of zone it gives +5% hp as its like destroyed (if left passive of Eearth c1 learnt) 

### Reproducible Bugs

Learn Earth skill c1 (Rock'n'Roll) for 7/7 + left passive of c1 (for +5% hp after Rock gets destroyed) then wait for red zone - use skill in red zone and give zone to destroy Rock - and then Rock become immortal and every tick of zone it gives +5% hp as its like get destroyed

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeiron-doodaria) channel and reference the specific issue on Github.

**Comment by Spartacus00007** [comment] 2024-01-31 03:35
![1](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/158244007/dac6d601-0600-4b2f-9dc7-a55475f0e9a7)
![2](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/assets/158244007/0276e5d7-32c5-4983-ad5c-fe0e3f3eb137)
2 screenshots with different times, the life of the balls was lost, but they did not break and continue to restore the life of the avatar

**Comment by gemscng** [comment] 2024-02-04 14:37
duplicate of #83

**Closed as completed by gemscng** 2024-02-04 14:37 UTC
Labels: bug, beta
